# Generated by Django 4.1.7 on 2023-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_id_alter_scope_topic_alter_topic_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tag',
            new_name='topic',
        ),
    ]
