# Generated by Django 4.1.7 on 2023-06-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_tag_topic_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='topic',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='topic',
            new_name='tag',
        ),
    ]
