# Generated by Django 4.1.7 on 2023-06-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_topic_tag_rename_topic_scope_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='topic',
        ),
    ]
