# Generated by Django 4.1.7 on 2023-06-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_rename_tag_scope_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Topic',
        ),
    ]
