# Generated by Django 4.1.7 on 2023-06-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_tag_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='tag',
        ),
    ]
