# Generated by Django 4.1.7 on 2023-06-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_topic_topic_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
