# Generated by Django 4.1.7 on 2023-06-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.topic', verbose_name='Тематика статьи'),
        ),
    ]
